Repository bw-table/bw-table-front, pull requests merged in 2024-10, with the labels that each got.

#4 Feature/3/공통 버튼 및 인풋 컴포넌트 구현
  .eslintrc.cjs
  .prettierrc.cjs
  src/components/common/button/Button.stories.ts
  src/components/common/button/Button.tsx
  src/components/common/button/CommonButton.stories.ts
  src/components/common/button/CommonButton.tsx
  src/components/common/input/CommonInput.stories.ts
  src/components/common/input/CommonInput.tsx
  src/components/common/input/FormInput.stories.tsx
  src/components/common/input/FormInput.tsx
  src/components/feature/example/ExampleComponent.tsx
  src/types/components.ts
  tailwind.config.ts
Labels: enhancement

#7 Feature/6/회원가입 페이지 마크업 및 React-hook-form 연동
  .idea/prettier.xml
  .storybook/preview.ts
  next.config.ts
  package.json
  public/KakaoLogo.svg
  public/Logo.svg
  src/app/(auth)/auth/page.tsx
  src/app/(auth)/auth/signin/page.tsx
  src/app/(auth)/auth/signup/page.tsx
  src/app/(auth)/layout.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/button/CommonButton.tsx
  src/components/common/input/FormInput.tsx
  src/components/feature/signup/SignupForm.tsx
  src/components/feature/signup/ValidationMessage.tsx
  src/components/layout/Container.tsx
  src/constants/regex.ts
  src/constants/validationRules.ts
  src/types/components.ts
  tailwind.config.ts
  tsconfig.json
  yarn.lock
Labels: enhancement, style

#9 Refactor/8/공통 컴포넌트 리팩토링 및 회원가입 페이지 UI 개선
  public/Check.svg
  src/app/(auth)/auth/signup/page.tsx
  src/components/common/button/CommonButton.tsx
  src/components/common/input/CommonInput.tsx
  src/components/common/input/FormInput.tsx
  src/components/feature/signup/SignupForm.tsx
  src/components/feature/signup/ValidationMessage.tsx
  src/constants/validationRules.ts
  src/types/components.ts
  src/types/form.ts
  src/types/index.ts
  tailwind.config.ts
Labels: style, refactor

#11 Feature/5/예약 페이지 마크업 및 공통 컴포넌트 구현
  .eslintrc.cjs
  .vscode/settings.json
  package.json
  src/app/(member)/@modal/(.)reservations/page.tsx
  src/app/(member)/@modal/default.tsx
  src/app/(member)/layout.tsx
  src/app/(member)/restaurants/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/calendar/CommonCalendar.stories.ts
  src/components/common/calendar/CommonCalendar.tsx
  src/components/common/modal/CommonModal.stories.tsx
  src/components/common/modal/CommonModal.tsx
  src/components/feature/ReservationConfirm.tsx
  src/components/feature/ReservationForm.tsx
  src/components/feature/example/ExampleComponent.tsx
  src/types/components.ts
  src/types/response.ts
  src/utils/cn.ts
  tailwind.config.ts
  yarn.lock
Labels: enhancement, style
