Repository bw-table/bw-table-front, pull requests merged in 2024-11, with the labels that each got.

#13 Feature/12/예약 페이지 목데이터 연동 및 상태관리 수정
  src/app/(member)/@modal/(.)reservations/page.tsx
  src/app/(member)/layout.tsx
  src/app/layout.tsx
  src/components/feature/reservation/ReservationConfirm.tsx
  src/components/feature/reservation/ReservationForm.tsx
  src/constants/endPoint.ts
  src/hooks/queries/reservation/usePostReservation.ts
  src/mocks/db/db.ts
  src/mocks/handlers.ts
  src/types/components.ts
  src/types/request.ts
Labels: enhancement, refactor

#14 Feature/#10/Axios 인스턴스 추가 및 회원가입 페이지 목데이터 연동
  package.json
  src/api/axiosInstance.ts
  src/components/common/input/CommonInput.stories.ts
  src/components/feature/signup/SignupForm.tsx
  src/components/feature/signup/ValidationMessage.tsx
  src/constants/endPoint.ts
  src/constants/regex.ts
  src/constants/validationRules.ts
  src/hooks/queries/auth/useSignUp.ts
  src/hooks/queries/auth/useSignupDuplicate.ts
  src/hooks/useDebounce.ts
  src/hooks/useWatchDuplicate.ts
  src/mocks/db/db.ts
  src/mocks/handlers.ts
  src/store/auth/index.ts
  src/store/auth/slice/duplicateSlice.ts
  src/store/index.ts
  src/types/form.ts
  src/types/request.ts
  src/types/store.ts
  yarn.lock
Labels: enhancement

#17 Feature/#15/로그인 페이지 마크업 및 목데이터 연동
  src/api/axiosInstance.ts
  src/api/interceptors.ts
  src/app/(auth)/auth/signin/page.tsx
  src/components/feature/signup/SigninForm.tsx
  src/components/feature/signup/SignupForm.tsx
  src/constants/endPoint.ts
  src/hooks/queries/auth/useSignIn.ts
  src/hooks/useSignupRules.ts
  src/mocks/db/db.ts
  src/mocks/handlers.ts
  src/types/form.ts
  src/types/request.ts
  src/utils/tokenManager.ts
Labels: enhancement, style

#21 Feature/#18/식당 상세 정보 페이지 마크업 및 목데이터 연동
  src/app/(member)/layout.tsx
  src/app/(member)/restaurants/[id]/page.tsx
  src/app/(member)/restaurants/page.tsx
  src/components/common/divider/CommonDivider.stories.tsx
  src/components/common/divider/CommonDivider.tsx
  src/components/common/navigation-bar/CommonNavigationBar.stories.tsx
  src/components/common/navigation-bar/CommonNavigationBar.tsx
  src/constants/endPoint.ts
  src/hooks/queries/restaurant/useGetRestaurantDetail.ts
  src/mocks/db/db.ts
  src/mocks/handlers.ts
  src/types/request.ts
Labels: enhancement

#24 Refactor/#22/ 식당 상세 정보 페이지 UI수정 및 컴포넌트 분리
  public/mockServiceWorker.js
  src/app/(member)/restaurants/[id]/page.tsx
  src/components/common/divider/CommonDivider.tsx
  src/components/feature/restaurant/RestaurantAnnouncement.tsx
  src/components/feature/restaurant/RestaurantDetailInfo.tsx
  src/components/feature/restaurant/RestaurantFacilities.tsx
  src/components/feature/restaurant/RestaurantMenuTab.tsx
  src/components/feature/restaurant/RestaurantReviewTab.tsx
  src/components/feature/restaurant/ResturantHome.tsx
  src/constants/icons.ts
  src/constants/queryKeys.ts
  src/constants/restaurantCategory.ts
  src/hooks/queries/restaurant/useGetAnnouncement.ts
  src/hooks/queries/restaurant/useGetRestaurantDetail.ts
  src/hooks/queries/restaurant/useGetReviewList.ts
  src/mocks/db/db.ts
  src/mocks/handlers.ts
  src/types/form.ts
  src/types/request.ts
  yarn.lock
Labels: enhancement, style, refactor

#26 Feature/#25/마이페이지&마이다이닝 마크업 UI 구현 및 목데이터 연동
  public/assets/profile-default.png
  src/app/(member)/my-dining/page.tsx
  src/app/(member)/my-page/page.tsx
  src/app/(member)/restaurants/[id]/page.tsx
  src/components/common/header/CommonHeader.stories.ts
  src/components/common/header/CommonHeader.tsx
  src/components/common/navigation-bar/BottomNavigationBar.tsx
  src/components/feature/my-page/MyReservationList.tsx
  src/components/feature/restaurant/RestaurantAnnouncement.tsx
  src/constants/endPoint.ts
  src/constants/queryKeys.ts
  src/hooks/queries/reservation/useGetReservations.ts
  src/hooks/queries/reservation/usePostReservation.ts
  src/hooks/queries/restaurant/useGetAnnouncement.ts
  src/hooks/queries/restaurant/useGetReviewList.ts
  src/mocks/db/db.ts
  src/mocks/handlers.ts
  src/types/form.ts
  src/types/request.ts
Labels: bug, enhancement, refactor

#29 Feature/#28/나의 가게 등록 페이지 마크업 구현 및 msw 연동
  package.json
  src/app/(management)/@modal/default.tsx
  src/app/(management)/@modal/menus/page.tsx
  src/app/(management)/layout.tsx
  src/app/(management)/new-restaurant/page.tsx
  src/app/(member)/my-dining/page.tsx
  src/components/common/header/CommonHeader.tsx
  src/components/common/modal/CommonModal.tsx
  src/components/common/textarea/CommonTextArea.tsx
  src/components/feature/management/AddressInput.tsx
  src/components/feature/management/CategorySelect.tsx
  src/components/feature/management/FacilitiesSelect.tsx
  src/components/feature/management/HashTagInput.tsx
  src/components/feature/management/OperatingHoursForm.tsx
  src/components/feature/management/RestaurantImageUpload.tsx
  src/constants/endPoint.ts
  src/hooks/queries/restaurant/usePostRestaurant.ts
  src/mocks/handlers.ts
  src/store/restaurant/useMenuStore.ts
  src/types/form.ts
  src/types/request.ts
  yarn.lock
Labels: enhancement, refactor
